### ISSUE TITLE
SIGSEGV when processing XLS file with log2timeline

### ISSUE THREAD

**Issue by ge0rg** [libyal/libolecf#1]
When parsing certain XLS files with the olecf filter, the log2timeline worker crashes with a SIGSEGV. Tested with plaso from git (2015-02-05, log2timeline/plaso@e9b14ef7dc2fa55697dfd499f2bd5ec265f85bac) and it's according dependenices (libolecf-20150106).

Unfortunately, I can not provide the XLS file that caused the crash, but here is a stack trace from libolecf:

```
Source path				: /home/georg/l2t-debug-1/b.xls
Is storage media image or device	: False

[err!] [/] Error: Seek above field set end (1988542760960.0)
[err!] [/] Error: Unable to add property[8]content[0]: field is too large

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe80e2bb0 in libolecf_io_handle_read_stream (io_handle=0x152b140, file_io_handle=0x1cbe250, sat=0x1b8a960, ssat=0x19ade10, directory_entry=0x14d0c60, offset=0xaec718, 
    buffer=0x7fffffffc920 "\200", size=28, error=0x7fffffffc9d0) at libolecf_io_handle.c:2508
2508					short_sector_stream_sector_identifier = sat->sector_identifier[ short_sector_stream_sector_identifier ];
(gdb) bt
#0  0x00007fffe80e2bb0 in libolecf_io_handle_read_stream (io_handle=0x152b140, file_io_handle=0x1cbe250, sat=0x1b8a960, ssat=0x19ade10, directory_entry=0x14d0c60, offset=0xaec718, 
    buffer=0x7fffffffc920 "\200", size=28, error=0x7fffffffc9d0) at libolecf_io_handle.c:2508
#1  0x00007fffe80e865a in libolecf_stream_read_buffer (item=0xaec6f0, buffer=0x7fffffffc920 "\200", size=28, error=0x7fffffffc9d0) at libolecf_stream.c:134
#2  0x00007fffe80e5b7f in libolecf_property_set_read (property_set=0x17a96a0, io_handle=0x152b140, property_set_stream=0xaec6f0, error=0x7fffffffc9d0) at libolecf_property_set.c:231
#3  0x00007fffe80e656c in libolecf_property_set_stream_get_set (property_set_stream=0xaec6f0, property_set=0x7fffffffc9c8, error=0x7fffffffc9d0) at libolecf_property_set_stream.c:93
#4  0x00007fffe841cd6e in pyolecf_property_set_stream_get_set (pyolecf_item=0x7fffe6fe4bf0, arguments=0x0) at pyolecf_property_set_stream.c:187
#5  0x00000000004dfc5e in ?? ()
#6  0x00000000004b2885 in PyObject_GetAttr ()
#7  0x00000000004caa61 in PyEval_EvalFrameEx ()
#8  0x00000000004e6cf0 in ?? ()
#9  0x00000000005052e8 in ?? ()
#10 0x0000000000504313 in ?? ()
#11 0x00000000004bb18b in ?? ()
#12 0x00000000004cb879 in PyEval_EvalFrameEx ()
#13 0x00000000004c94b9 in PyEval_EvalCodeEx ()
#14 0x00000000004cb0fc in PyEval_EvalFrameEx ()
#15 0x00000000004c94b9 in PyEval_EvalCodeEx ()
#16 0x00000000004cb0fc in PyEval_EvalFrameEx ()
#17 0x00000000004c94b9 in PyEval_EvalCodeEx ()
#18 0x00000000004cb0fc in PyEval_EvalFrameEx ()
#19 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#20 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#21 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#22 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#23 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#24 0x00000000004c94b9 in PyEval_EvalCodeEx ()
#25 0x00000000004cb0fc in PyEval_EvalFrameEx ()
#26 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#27 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#28 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#29 0x00000000004cb3ba in PyEval_EvalFrameEx ()
#30 0x00000000004c94b9 in PyEval_EvalCodeEx ()
#31 0x0000000000503dff in ?? ()
---Type <return> to continue, or q <return> to quit---
#32 0x00000000004f9412 in PyRun_FileExFlags ()
#33 0x00000000004f8507 in PyRun_SimpleFileExFlags ()
#34 0x0000000000498ded in Py_Main ()
#35 0x00007ffff6f14b45 in __libc_start_main (main=0x498880 <main>, argc=8, argv=0x7fffffffe7b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe7a8)
    at libc-start.c:287
#36 0x00000000004987ab in _start ()
(gdb) 
```

**Comment by joachimmetz** [comment]
Thanks, I'll have a look as soon as possible. The back trace already gives me some information of where to look.

**Comment by joachimmetz** [comment]
Added more bounds checking: https://github.com/libyal/libolecf/commit/dc21d7e7a6c336420ca5b58fe122ede5fe9fc383

**Comment by joachimmetz** [comment]
Currently testing with AFL and adding more bounds checking.
